version: "3"
services:
  ethtxd:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-ethtxd
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /ethtxd
          nix-shell shell-bin.nix --run '/usr/bin/ethtxd -p 3000 -r https://nodes.mewapi.io/rpc/eth' --pure
    ports:
      - "3000:3000"
    expose:
      - "3000"
    healthcheck:
      test: curl localhost:3000
      interval: 5s
      timeout: 3s
      retries: 5

  miao-backend:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-miao-backend
    environment:
      - PORT=3001
      - ETHTXD_URL=http://ethtxd:3000
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /app
          yarn start
    ports:
      - "3001:3001"
    expose:
      - "3001"
    healthcheck:
      test: curl localhost:3001
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - ethtxd