version: "3"
services:
  ethtxd:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-ethtxd
    environment:
      - MEW_RPC_URL=https://nodes.mewapi.io/rpc/eth
      - BLOCK_SCOUT_RPC_URL=https://mainnet-nethermind.blockscout.com/
      - MY_CRYPTO_RPC_URL=https://api.mycryptoapi.com/eth
      - CLOUDFLARE_RPC_URL=https://cloudflare-eth.com/
      - PERSONAL_NODE=http://192.168.1.108:8544
      - LOCALHOST_NODE=http://192.168.1.106:8545
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /ethtxd
          nix-shell shell-bin.nix --run '/usr/bin/ethtxd -p 3002 -r https://nodes.mewapi.io/rpc/eth' --pure
    ports:
      - "3002:3002"
    expose:
      - "3002"
    healthcheck:
      test: curl localhost:3002
      interval: 5s
      timeout: 3s
      retries: 5

  miao-backend:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-miao-backend
    environment:
      - PORT=3001
      - ETHTXD_URL=http://ethtxd:3002
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /app
          yarn start
    ports:
      - "3001:3001"
    expose:
      - "3001"
    healthcheck:
      test: curl localhost:3001
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - ethtxd

  miao-frontend:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-miao-frontend
    environment:
      - BACKEND_URL=http://localhost:3001
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /app
          yarn serve
    ports:
      - "3000:3000"
    expose:
      - "3000"
    healthcheck:
      test: curl localhost:3000
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - miao-backend